// src/lib/ui-components/components/CodeBlock.tsx
import { Check, Copy } from 'lucide-react';
import { memo, useState } from 'react';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { oneDark, oneLight } from 'react-syntax-highlighter/dist/esm/styles/prism';
import { useTheme } from '../hooks/use-theme';

type CodeBlockProps = {
  language?: string;
  code: string;
};

export const CodeBlock = memo(({ language, code }: CodeBlockProps) => {
  const { theme } = useTheme();
  const style = theme === 'dark' ? oneDark : oneLight;
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="my-2 rounded-lg border border-border overflow-hidden relative group">
      <button
        type="button"
        onClick={handleCopy}
        className="absolute top-2 right-2 p-2 rounded-md bg-muted/80 hover:bg-muted hover:scale-110 active:scale-95 transition-all z-10"
        title="Copy to clipboard"
      >
        {copied ? (
          <Check size={16} className="text-green-500 animate-in fade-in zoom-in duration-200" />
        ) : (
          <Copy size={16} className="text-muted-foreground hover:text-foreground transition-colors" />
        )}
      </button>
      <SyntaxHighlighter
        language={language || 'text'}
        style={style}
        customStyle={{
          margin: 0,
          padding: '1rem',
          fontSize: '0.875rem',
          background: 'transparent'
        }}
        codeTagProps={{
          style: {
            fontFamily: 'monospace'
          }
        }}
      >
        {code}
      </SyntaxHighlighter>
    </div>
  );
});

CodeBlock.displayName = 'CodeBlock';

// src/session-view-page/webview/components/CodeBlock.svelte
<script lang="ts">
  import { Check, Copy } from 'lucide-svelte';
  import { Highlight } from 'svelte-highlight';
  import {
    bash,
    cpp,
    csharp,
    go,
    java,
    javascript,
    json,
    kotlin,
    php,
    python,
    ruby,
    rust,
    swift,
    typescript
  } from 'svelte-highlight/languages';
  import { atomOneDark, atomOneLight } from 'svelte-highlight/styles';
  import { theme } from '../utils/theme';

  interface Props {
    code: string;
    language?: string;
  }

  let { code, language = 'typescript' }: Props = $props();

  let copied = $state(false);

  const languageMap: Record<string, unknown> = {
    typescript,
    javascript,
    python,
    bash,
    json,
    go,
    rust,
    java,
    cpp,
    csharp,
    ruby,
    php,
    swift,
    kotlin,
    ts: typescript,
    js: javascript,
    py: python,
    sh: bash
  };

  function getLanguage(lang: string) {
    return languageMap[lang.toLowerCase()] || typescript;
  }

  async function copyCode() {
    await navigator.clipboard.writeText(code);
    copied = true;
    setTimeout(() => {
      copied = false;
    }, 2000);
  }
</script>

<svelte:head>
  {#if $theme === 'dark'}
    {@html atomOneDark}
  {:else}
    {@html atomOneLight}
  {/if}
</svelte:head>

<div class="relative group rounded-md overflow-hidden my-2">
  <button
    type="button"
    onclick={copyCode}
    class="absolute top-2 right-2 p-1.5 rounded bg-zinc-700/80 text-zinc-300
           opacity-0 group-hover:opacity-100 transition-opacity hover:bg-zinc-600"
  >
    {#if copied}
      <Check class="h-4 w-4 text-green-400" />
    {:else}
      <Copy class="h-4 w-4" />
    {/if}
  </button>

  <Highlight language={getLanguage(language)} {code} />
</div>
