// apps/vscode-extension/src/webview/components/FilterButtons.tsx
import { Cpu, User, Wrench } from 'lucide-react';
import { FilterButton } from './FilterButton';

type FilterButtonsProps = {
  showUserMessages: boolean;
  showAssistantMessages: boolean;
  showToolCalls: boolean;
  onToggleUser: () => void;
  onToggleAssistant: () => void;
  onToggleToolCalls: () => void;
};

export const FilterButtons = ({
  showUserMessages,
  showAssistantMessages,
  showToolCalls,
  onToggleUser,
  onToggleAssistant,
  onToggleToolCalls
}: FilterButtonsProps) => {
  return (
    <div className="flex items-center gap-2">
      <FilterButton
        isActive={showAssistantMessages}
        onClick={onToggleAssistant}
        title="Claude Code messages"
        ariaLabel="Claude Code messages"
        icon={<Cpu size={18} strokeWidth={showAssistantMessages ? 3 : 2} className="transition-all" />}
      />

      <FilterButton
        isActive={showUserMessages}
        onClick={onToggleUser}
        title="Your messages"
        ariaLabel="Your messages"
        icon={<User size={18} strokeWidth={showUserMessages ? 3 : 2} className="transition-all" />}
      />

      <FilterButton
        isActive={showToolCalls}
        onClick={onToggleToolCalls}
        title="Tool calls"
        ariaLabel="Tool calls"
        icon={<Wrench size={18} strokeWidth={showToolCalls ? 3 : 2} className="transition-all" />}
      />
    </div>
  );
};

// src/session-view-page/webview/components/FilterButtons.svelte
<script lang="ts">
  import { Cpu, User, Wrench } from 'lucide-svelte';
  import { filtersStore } from '../stores';
  import FilterButton from './FilterButton.svelte';

  let showUserMessages = $derived($filtersStore.showUserMessages);
  let showAssistantMessages = $derived($filtersStore.showAssistantMessages);
  let showToolCalls = $derived($filtersStore.showToolCalls);
</script>

<div class="flex gap-1">
  <FilterButton isActive={showUserMessages} onclick={() => filtersStore.toggle('showUserMessages')}>
    <User class="h-4 w-4" strokeWidth={showUserMessages ? 2.5 : 1.5} />
  </FilterButton>

  <FilterButton isActive={showAssistantMessages} onclick={() => filtersStore.toggle('showAssistantMessages')}>
    <Cpu class="h-4 w-4" strokeWidth={showAssistantMessages ? 2.5 : 1.5} />
  </FilterButton>

  <FilterButton isActive={showToolCalls} onclick={() => filtersStore.toggle('showToolCalls')}>
    <Wrench class="h-4 w-4" strokeWidth={showToolCalls ? 2.5 : 1.5} />
  </FilterButton>
</div>
