// packages/ui-components/src/components/SessionBadges.tsx
import { FileText, Image, Link, Search, Terminal } from 'lucide-react';
import type { SessionCardData } from '../types/session';
import { IconWithBadge } from './IconWithBadge';

type SessionBadgesProps = {
  session: SessionCardData;
  showSearch?: boolean;
};

export const SessionBadges = ({ session, showSearch = false }: SessionBadgesProps) => {
  return (
    <>
      {showSearch && session.searchMatchCount !== undefined && session.searchMatchCount > 0 && (
        <span className="text-primary">
          <IconWithBadge icon={Search} count={session.searchMatchCount} label={`${session.searchMatchCount} matches`} />
        </span>
      )}
      {session.imageCount !== undefined && session.imageCount > 0 && (
        <IconWithBadge icon={Image} count={session.imageCount} label={`${session.imageCount} images`} />
      )}
      {session.customCommandCount !== undefined && session.customCommandCount > 0 && (
        <IconWithBadge
          icon={Terminal}
          count={session.customCommandCount}
          label={`${session.customCommandCount} custom commands`}
        />
      )}
      {session.filesOrFoldersCount !== undefined && session.filesOrFoldersCount > 0 && (
        <IconWithBadge
          icon={FileText}
          count={session.filesOrFoldersCount}
          label={`${session.filesOrFoldersCount} files/folders`}
        />
      )}
      {session.urlCount !== undefined && session.urlCount > 0 && (
        <IconWithBadge icon={Link} count={session.urlCount} label={`${session.urlCount} URLs`} />
      )}
    </>
  );
};

// src/session-view-page/webview/components/SessionBadges.svelte
<script lang="ts">
  import { FolderOpen, Image } from 'lucide-svelte';
  import { filesOrFoldersCount, sessionStore } from '../stores';
  import IconWithBadge from './IconWithBadge.svelte';

  let session = $derived($sessionStore?.session);
  let images = $derived($sessionStore?.conversation?.images || []);
</script>

{#if session}
  <div class="flex items-center gap-3">
    {#if images.length > 0}
      <IconWithBadge icon={Image} count={images.length} label="Images" />
    {/if}

    {#if $filesOrFoldersCount > 0}
      <IconWithBadge icon={FolderOpen} count={$filesOrFoldersCount} label="Files/Folders" />
    {/if}

    {#if session.tokenPercentage !== undefined}
      <div class="flex items-center gap-1 text-zinc-400" title="Token usage">
        <span class="text-xs">{session.tokenPercentage}%</span>
      </div>
    {/if}
  </div>
{/if}
