// apps/vscode-extension/src/webview/components/SessionContent.tsx
import { type SessionImage, SessionMessage, type SessionMessageType } from '@better-claude-code/ui-components';

type SessionContentProps = {
  groupedMessages: SessionMessageType[][];
  images: SessionImage[];
  onImageClick: (imageIndex: number) => void;
};

export const SessionContent = ({ groupedMessages, images, onImageClick }: SessionContentProps) => {
  return (
    <div style={{ flex: 1, overflowY: 'auto', minHeight: 0 }}>
      <div className="max-w-4xl mx-auto p-5">
        <div className="space-y-2">
          {groupedMessages.map((messages) => {
            const firstMessage = messages[0];
            return (
              <SessionMessage
                key={firstMessage.id}
                messages={messages}
                imageOffset={0}
                onImageClick={onImageClick}
                images={images}
                availableImages={images.map((img) => img.index)}
              />
            );
          })}
        </div>
      </div>
    </div>
  );
};

// src/session-view-page/webview/components/SessionContent.svelte
<script lang="ts">
  import { groupedMessages, sessionStore } from '../stores';
  import { vscode } from '../utils/vscode';
  import SessionMessage from './SessionMessage.svelte';

  let images = $derived($sessionStore?.conversation?.images || []);

  function handleImageClick(imageIndex: number) {
    const image = images[imageIndex];
    if (image) {
      vscode.postMessage({
        type: 'openImage',
        imageData: image.data,
        imageIndex: image.index
      });
    }
  }
</script>

<div class="flex-1 overflow-y-auto min-h-0">
  <div class="max-w-4xl mx-auto p-4">
    <div class="space-y-2">
      {#each $groupedMessages as messages, idx (idx)}
        <SessionMessage
          {messages}
          onImageClick={handleImageClick}
          {images}
          availableImages={images.map((img) => img.index)}
        />
      {/each}

      {#if $groupedMessages.length === 0}
        <div class="text-center text-muted-foreground py-8">No messages to display</div>
      {/if}
    </div>
  </div>
</div>
